version: '3.0'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.10
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - ek-net
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana:7.17.10
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ek-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
networks:
  ek-net:
    driver: bridge